---
- name: diksha
  hosts: all

  #vars_files:
  #- data.yml

  #vars_prompt:
  #- name: a
  #prompt: "kk prompt"
  #private: no

  #vars:
  #a: "this msg from global variable"

  tasks:
   - name: task-1
     vars:
       a: "this msg is from local variable"
     debug:
       msg: "{{a}}"

   - name: task-2
     vars:
       b: "this msg is from task-2 local variable"
     debug:
       msg: "{{b}}"


...

